import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Locale, PortfolioReport, SectionId } from '@devportfolio/core';
import { Eta } from 'eta';

const here = dirname(fileURLToPath(import.meta.url));
// templates/ is shipped alongside the compiled JS by the package build step.
const TEMPLATES_DIR = join(here, 'templates');

export interface RenderMarkdownOptions {
  report: PortfolioReport;
  sections: SectionId[];
  locale: Locale;
  templatesDir?: string;
}

export async function renderMarkdown({
  report,
  sections,
  locale,
  templatesDir = TEMPLATES_DIR,
}: RenderMarkdownOptions): Promise<string> {
  const eta = new Eta({
    views: join(templatesDir, locale),
    cache: true,
    autoTrim: false,
  });

  const blocks: string[] = [];
  for (const section of sections) {
    const rendered = await eta.renderAsync(`${section}.eta`, { report });
    if (rendered && rendered.trim().length > 0) blocks.push(rendered.trim());
  }

  blocks.push(receipt(report));
  return blocks.join('\n\n');
}

function receipt(report: PortfolioReport): string {
  const ts = report.generatedAt.replace('T', ' ').slice(0, 16);
  return `<sub>Generated by [DevPortfolio](https://github.com/AbdullahBakir97/devportfolio) at ${ts} UTC</sub>`;
}
